spring:
  application:
    name: climalert

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    url: ${WEATHER_API_URL:https://api.weatherapi.com/v1}
    key: ${WEATHER_API_KEY}
    location: ${WEATHER_API_LOCATION:-34.6037,-58.3816}

alertas:
  email:
    destinatario: ${ALERTA_EMAIL_DESTINO}

  valores-criticos:
    temperatura: ${TEMPERATURA_CRITICA:35}
    humedad: ${HUMEDAD_CRITICA:60}